-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 20:00:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notes` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema notitas
-- -----------------------------------------------------
USE `notes` ;

-- -----------------------------------------------------
-- Table `notes`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `body` TEXT(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notes`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes`.`topics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topic_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_topic_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `notes`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notes`.`topic_has_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notes`.`topic_has_notes` (
  `topic_id` INT NOT NULL,
  `note_id` INT NOT NULL,
  PRIMARY KEY (`topic_id`, `note_id`),
  INDEX `fk_topic_has_notes_notes1_idx` (`note_id` ASC),
  INDEX `fk_topic_has_notes_topic1_idx` (`topic_id` ASC),
  CONSTRAINT `fk_topic_has_notes_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `notes`.`topics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_has_notes_note1`
    FOREIGN KEY (`note_id`)
    REFERENCES `notes`.`notes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
